services:
  - type: web
    name: finai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_server:app --config gunicorn_config.py
    envVars:
      - key: FLASK_ENV
        value: production